### PR TITLE
Add property for languages

### PR DESCRIPTION
**Pull request by ranju30**
1. Refactored banner.jsp to remove unnecessary 'if statements' for showing language change message.
2. Now we show Dropdown instead of buttons, to change language on Login Page.
3. Added Spanish language support. We still need to translate the properties file to Spanish.

Now, the steps to add support for a new language in OpenELIS are:
1. add international code and language in SetOfSupportedLanguages.properties
2. add language change message in SetOfSupportedLanguages.properties
3. add the language to see in dropdown In banner.jsp 
4. add the update message in banner.jsp
5. add a new property file with the name MessageResource_<languagecode>.properties in location: openelis/src folder

### CODE REVIEW

**Comment by ranju30** [comment]
While doing Internationalization the text length was longer than the size of each row, So It was not all the given option, basically "print" option was outside the row.
So I added Icons for those three links and on hover it will show the name of the link.

**Comment by gsluthra** [comment]
Because we can't control the size of the words after being translated, we discovered that the Print option would get truncated in such cases, from the table column. Hence, after discussions with some UI devs, it was suggested to use icons instead of words, and provide a tooltip for them. That way, the icons will be independent of the language. 

@ranju30  Can you please attach a screenshot of how it looks now?

**Comment by ranju30** [comment]
Sure here is the preview of how it looks 
[http://pasteboard.co/1uZzGic9.png](url)

**Comment by ranju30** [comment]
Special characters were showing differently, So I have added unicode for those special characters.

**Comment by gsluthra** [comment]
Added a card in mingle for this: https://bahmni.mingle.thoughtworks.com/projects/bahmni_emr/cards/1918

**Comment by HemanthGowda** [comment]
I don't see dropdown to change the language in OpenELIS login page. Am I missing something?

**Comment by HemanthGowda** [comment]
update site_information set value=true where name='allowLanguageChange';

to show dropdown to change language in openelis

**Comment by gsluthra** [comment]
The SQL was documented here on WIKI: https://bahmni.atlassian.net/wiki/display/BAH/Product+Internationalization

**Pull request merged**
