### PR TITLE
bindu | Added Support for Portuguese Language

### PR DESCRIPTION
**Pull request by binduak**
screen shot 2016-08-09 at 7 54 04 am

### CODE REVIEW

**Comment by gsluthra** [comment]
Is this reviewed and ready for merge?

**Comment by padmavati** [comment]
This is not tested yet. I will test and merge.

**Comment by padmavati** [comment]
Hi,
1)The above pull request is not having the translations for LabDashboard page.
screen shot 2016-08-22 at 4 33 54 pm

2)It is having partial translations for Edit Sample page
screen shot 2016-08-22 at 4 35 12 pm

3)It is not having translations for Test Status By Patient on Status Report page
screen shot 2016-08-22 at 4 37 58 pm

4)It is not having translations for All Tests summary page under Aggregate Reports
screen shot 2016-08-22 at 4 40 29 pm

**Comment by gsluthra** [comment]
Yay! Thank you!

**Pull request merged**
